# config/saturation_matrix.yaml
# Configuration file specifically for finding the 1-GPU saturation point.
meta:
  default_run_time: "1m"  # Shorter run time for quicker saturation tests
  repetitions: 1
  output_root: "results/raw_saturation"

common_env:
  VLLM_MODEL_PATH: "/home/user1/ADD-LLM-service/llm/Qwen3-14B/"
  VLLM_PORT: 18806
  VLLM_MODEL: "qwen3"
  REQUEST_TIMEOUT: 120

factors:
  gpu_counts: [1]
  request_rates: [10, 20, 30, 40, 50, 60] # Incrementally increasing load
  prompt_len_profile: ["medium"] # Fixed profile to reduce variables
  batch_size: [16] # Fixed batch size
  max_batched_tokens: [512]
  data_parallel: [1]
  tensor_parallel: [1]
  quant_mode: ["fp16"]

profiles:
  short:
    prompts_file: config/prompts_short.jsonl
    max_tokens: 64
  medium:
    prompts_file: config/prompts_medium.jsonl
    max_tokens: 128
  long:
    prompts_file: config/prompts_long.jsonl
    max_tokens: 256
